os:
  - windows
  - linux
  - osx

addons:
  apt:
    packages:
    - autopoint

language: c

env:
  - BRANCH=0.20.2
  - BRANCH=1.0.6
  - BRANCH=1.2.2
  - BRANCH=devel

cache:
  directories:
    - "$HOME/.choosenim"

install:
  - export PATH="/usr/local/opt/gettext/bin:$PATH"
  - curl https://gist.github.com/genotrance/fb53504a4fba88bc5201d3783df5c522/raw/travis.sh -LsSf -o travis.sh
  - source travis.sh

script:
  - nimble develop -y
  - nimble test
  - nimble --verbose --nimbleDir:`pwd`/build/fakenimble install nimterop@#head -y
